In [ ]:
from mgwr.gwr import GWR as OfficialGWR
from mgwr.sel_bw import Sel_BW

from src.log.gwr_logger import GwrLogger
from src.optimizer.gwr_optimizer import GwrOptimizer
from src.kernel.gwr_kernel import GwrKernel
from src.model.gwr import GWR
from src.dataset.interfaces.idataset import FieldInfo
from src.dataset.spatial_dataset import SpatialDataset


In [7]:
from src.dataset.simulated_spatial_dataset import SimulatedSpatialDataset

# Create a logger to record the GWR model's information.
logger = GwrLogger()

# Load the Georgia dataset and create a spatial dataset.
field_size = 40
dataset = SimulatedSpatialDataset(field_size=field_size)
[X] = dataset.generate_data()
[beta] = dataset.generate_processes()
[y, err] = dataset.fit_y(X, beta)

In [8]:
# Create a GWR kernel and GWR model.
kernel = GwrKernel(dataset, 'bisquare')
gwr = GWR(dataset, kernel, logger)

# Use the bandwidth optimizer to automatically find the optimal bandwidth.
optimizer = GwrOptimizer(gwr, kernel, logger)
optimal_bandwidth = optimizer.optimize()

{'2025-09-24 15:47:55': 'GWR : GWR model is initialized.'}
{'2025-09-24 15:47:56': 'GwrOptimizer : Bandwidth 107.29490168751578, AICc 4767.060466308392, R2 0.9193576062626369'}
{'2025-09-24 15:47:58': 'GwrOptimizer : Bandwidth 142.7050983124842, AICc 4831.279922533137, R2 0.9122460739451383'}
{'2025-09-24 15:47:59': 'GwrOptimizer : Bandwidth 85.41019662496845, AICc 4741.935267760401, R2 0.9248752497428862'}
{'2025-09-24 15:48:01': 'GwrOptimizer : Bandwidth 71.88470506254731, AICc 4729.29535914662, R2 0.9270537985438609'}
{'2025-09-24 15:48:03': 'GwrOptimizer : Bandwidth 63.52549156242114, AICc 4742.079403530264, R2 0.9305935530063059'}
{'2025-09-24 15:48:04': 'GwrOptimizer : Bandwidth 77.05098312484228, AICc 4735.345867123666, R2 0.9262549921551493'}
{'2025-09-24 15:48:06': 'GwrOptimizer : Bandwidth 68.69176962471609, AICc 4747.0154595426775, R2 0.9295272797018631'}
{'2025-09-24 15:48:08': 'GwrOptimizer : Bandwidth 73.85804768701105, AICc 4731.05877578169, R2 0.9268336208812432'}
{'202

In [9]:

g_X = dataset.X[:, 1:]
g_y = dataset.y.reshape(-1, 1)
g_coords = dataset.coordinates.tolist()

gwr_selector = Sel_BW(g_coords, g_y, g_X)
gwr_bw = gwr_selector.search(bw_min=2)
official_gwr = OfficialGWR(g_coords, g_y, g_X, gwr_bw).fit()

In [10]:
print("Custom GWR R2:", gwr.r_squared)
print("Official GWR R2:", official_gwr.R2)

Custom GWR R2: 0.9272672768794565
Official GWR R2: 0.9272672768794565


In [11]:
print(gwr.aic)
print(gwr.aicc)
print(official_gwr.aic)
print(official_gwr.aicc)

4683.6349745085445
4727.937169193568
4683.6349745085445
4727.9371691935685


In [12]:
print(gwr.betas)
print(official_gwr.params)

[[ 2.1610449   1.72030713 -1.03442386]
 [ 2.26166029  1.71361625 -1.09773373]
 [ 2.35555652  1.76201787 -1.12697823]
 ...
 [ 0.3380878   1.16869785  2.53474891]
 [ 0.25832503  1.17317547  2.54279249]
 [ 0.24405102  1.16370717  2.54320856]]
[[ 2.1610449   1.72030713 -1.03442386]
 [ 2.26166029  1.71361625 -1.09773373]
 [ 2.35555652  1.76201787 -1.12697823]
 ...
 [ 0.3380878   1.16869785  2.53474891]
 [ 0.25832503  1.17317547  2.54279249]
 [ 0.24405102  1.16370717  2.54320856]]


In [13]:
print(gwr.kernel.bandwidth)
print(gwr_bw)

70.00000016298358
70.0
